services:
  service:
    two:
      url: localhost:8181/api/service/two
    three:
      url: localhost:8282/api/service/three

logging.level.com.demo.serviceone.feign: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: false
  okhttp:
    enabled: true